version: '3.3'

networks:
  redis_net:
    driver: bridge

services:
  redis:
    hostname: redis
    image: redis:7.0.4-alpine3.16
    networks:
      - redis_net
  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
    - REDIS_HOSTS=local:redis:6379
    networks:
      - redis_net
    ports:
    - 8081:8081