version: '3.3'

networks:
  db_net:
    driver: bridge

services:
  mogo-express:
    image: mongo-express:0.54.0
    ports:
    - 8081:8081
    networks:
    - db_net
    depends_on:
    - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
  mongo:
    image: mongo:5.0
    ports:
    - 27017:27017
    networks:
    - db_net
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
