version: '3.3'

networks:
  php_net:
    driver: bridge

services:
  phpmyadmin:
    image: phpmyadmin:5.2.0
    restart: always
    networks:
      - php_net
    ports:
      - 8080:80
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: test
      MARIADB_DATABASE: database
      MARIADB_ROOT_PASSWORD: admin
      PMA_HOST: maria_db
  maria_db:
    image: mariadb:10.6
    networks:
      - php_net
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_USER: admin
      MARIADB_PASSWORD: test
      MARIADB_DATABASE: database
