version: '3.3'

networks:
  php_net:
    driver: bridge

services:
  phpmyadmin:
    image: phpmyadmin:5.2.0
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  maria_db:
    image: mariadb:10.6
    networks:
      - php_net
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: admin