version: '3.3'

networks:
  word_net:
    driver: bridge

services:
  db:
    image: mysql:5.7
    networks:
      - word_net
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
  wordpress:
    depends_on:
      - db
    image: wordpress:php8.1
    networks:
      - word_net
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: admin